### ISSUE TITLE
importing externally created schedule

### ISSUE THREAD

**Issue by Andrej-Adamenko** [HelenFoster/AnkiSpreadsheetImportPlus#2]
You might want to consider adding the following feature: [importing externally created schedule (due dates, intervals, ease factors)](https://forums.ankiweb.net/t/importing-externally-created-schedule-from-a-text-file/2767) along with the data fields.
 That would help people who want to move their data and schedule from non-Anki programs or methods to Anki, or, if the scheduling data could be exported from Anki to a spreadsheet somehow, they could be edited and imported back then.

**Comment by HelenFoster** [comment]
It's an interesting thought. Not something I want to prioritise right now, but maybe sometime.

**Comment by HelenFoster** [comment]
Due to the way it works, this would actually be a different add-on.
